package payment

// AMMOffer represents a synthetic offer generated from an AMM pool.
// It mirrors the CLOB TOffer interface for generic use in BookStep's
// execOffer and consumeOffer paths.
//
// Reference: rippled/src/xrpld/app/paths/AMMOffer.h and detail/AMMOffer.cpp

import (
	"errors"

	"github.com/LeJamon/goXRPLd/keylet"
	tx "github.com/LeJamon/goXRPLd/internal/tx"
	"github.com/LeJamon/goXRPLd/internal/ledger/state"
)

// AMMOffer is a synthetic offer generated by AMMLiquidity.
type AMMOffer struct {
	ammLiquidity *AMMLiquidity

	// amountIn/amountOut are the offer amounts (takerPays/takerGets)
	amountIn  tx.Amount
	amountOut tx.Amount

	// balanceIn/balanceOut are the current pool state at offer creation time
	balanceIn  tx.Amount
	balanceOut tx.Amount

	// quality is the offer quality
	quality Quality

	// consumed is true after the offer has been consumed
	consumed bool
}

// NewAMMOffer creates a new AMM offer with quality derived from the offer amounts.
// Use NewAMMOfferWithBalanceQuality for maxOffer where quality should reflect pool spot price.
func NewAMMOffer(liq *AMMLiquidity, in, out, balIn, balOut tx.Amount) *AMMOffer {
	q := QualityFromAmounts(toEitherAmt(in), toEitherAmt(out))
	return &AMMOffer{
		ammLiquidity: liq,
		amountIn:     in,
		amountOut:    out,
		balanceIn:    balIn,
		balanceOut:   balOut,
		quality:      q,
	}
}

// NewAMMOfferWithBalanceQuality creates an AMM offer whose quality is derived
// from the pool balances (spot price) rather than the offer amounts.
// This matches rippled's maxOffer() which uses Quality{balances}.
// Reference: rippled AMMLiquidity.cpp maxOffer() line 133 and 144
func NewAMMOfferWithBalanceQuality(liq *AMMLiquidity, in, out, balIn, balOut tx.Amount) *AMMOffer {
	q := QualityFromAmounts(toEitherAmt(balIn), toEitherAmt(balOut))
	return &AMMOffer{
		ammLiquidity: liq,
		amountIn:     in,
		amountOut:    out,
		balanceIn:    balIn,
		balanceOut:   balOut,
		quality:      q,
	}
}

// Quality returns the offer quality.
func (o *AMMOffer) Quality() Quality {
	return o.quality
}

// Owner returns the AMM account ID.
func (o *AMMOffer) Owner() [20]byte {
	return o.ammLiquidity.ammAccountID
}

// AmountIn returns the offer's takerPays.
func (o *AMMOffer) AmountIn() tx.Amount {
	return o.amountIn
}

// AmountOut returns the offer's takerGets.
func (o *AMMOffer) AmountOut() tx.Amount {
	return o.amountOut
}

// IsFunded returns true — AMM offers are always fully funded by the pool.
func (o *AMMOffer) IsFunded() bool {
	return true
}

// FullyConsumed returns true if the offer has been consumed.
func (o *AMMOffer) FullyConsumed() bool {
	return o.consumed
}

// Consume marks the offer as consumed and notifies the AMMContext.
// Reference: rippled AMMOffer.cpp consume()
func (o *AMMOffer) Consume() {
	o.consumed = true
	o.ammLiquidity.ammContext.SetAMMUsed()
}

// LimitOut adjusts the offer to produce at most 'limit' output.
// Multi-path: uses quality-based ceiling (proportional adjustment).
// Single-path: uses swapAssetOut for exact pool conservation.
// Reference: rippled AMMOffer.cpp limitOut()
func (o *AMMOffer) LimitOut(ofrIn, ofrOut, limit EitherAmount, roundUp bool, fixReducedV1 bool) (EitherAmount, EitherAmount) {
	if o.ammLiquidity.ammContext.MultiPath() {
		if fixReducedV1 {
			return o.quality.CeilOutStrict(ofrIn, ofrOut, limit, roundUp)
		}
		return o.quality.CeilOut(ofrIn, ofrOut, limit)
	}
	// Single path: use swap function for exact conservation
	limitAmt := eitherToAmount(limit)
	newIn := SwapAssetOut(
		o.balanceIn, o.balanceOut, limitAmt,
		o.ammLiquidity.tradingFee, o.ammLiquidity.fixAMMv1_1,
	)
	return toEitherAmt(newIn), limit
}

// LimitIn adjusts the offer to consume at most 'limit' input.
// Multi-path: uses quality-based ceiling.
// Single-path: uses swapAssetIn for exact pool conservation.
// Reference: rippled AMMOffer.cpp limitIn()
func (o *AMMOffer) LimitIn(ofrIn, ofrOut, limit EitherAmount, roundUp bool, fixReducedV2 bool) (EitherAmount, EitherAmount) {
	if o.ammLiquidity.ammContext.MultiPath() {
		if fixReducedV2 {
			return o.quality.CeilInStrict(ofrIn, ofrOut, limit, roundUp)
		}
		return o.quality.CeilIn(ofrIn, ofrOut, limit)
	}
	// Single path: use swap function
	limitAmt := eitherToAmount(limit)
	newOut := SwapAssetIn(
		o.balanceIn, o.balanceOut, limitAmt,
		o.ammLiquidity.tradingFee, o.ammLiquidity.fixAMMv1_1,
	)
	return limit, toEitherAmt(newOut)
}

// AdjustRates adjusts transfer rates for AMM offers.
// AMM doesn't charge transfer fee on the output side.
// Returns (ofrInRate, QUALITY_ONE).
// Reference: rippled AMMOffer.h adjustRates()
func (o *AMMOffer) AdjustRates(ofrInRate, ofrOutRate uint32) (uint32, uint32) {
	return ofrInRate, QualityOne
}

// CheckInvariant validates the AMM pool product invariant:
// (balanceIn + consumed.in) * (balanceOut - consumed.out) >= balanceIn * balanceOut
// Allows 1e-7 relative distance for rounding tolerance.
// Reference: rippled AMMOffer.cpp checkInvariant()
func (o *AMMOffer) CheckInvariant(consumedIn, consumedOut tx.Amount) bool {
	if consumedIn.Compare(o.amountIn) > 0 || consumedOut.Compare(o.amountOut) > 0 {
		return false
	}

	// Convert to Number for uniform arithmetic (XRP and IOU can be mixed)
	nBalIn := toNumber(o.balanceIn)
	nBalOut := toNumber(o.balanceOut)
	nConIn := toNumber(consumedIn)
	nConOut := toNumber(consumedOut)

	product := nBalIn.Mul(nBalOut, false)

	newBalIn := ammAdd(nBalIn, nConIn)
	newBalOut := ammSub(nBalOut, nConOut)
	newProduct := newBalIn.Mul(newBalOut, false)

	if newProduct.Compare(product) >= 0 {
		return true
	}

	// Check within relative distance (1e-7 tolerance)
	oneAmt := ammOne()
	productQ := QualityFromAmounts(NewIOUEitherAmount(product), NewIOUEitherAmount(oneAmt))
	newProductQ := QualityFromAmounts(NewIOUEitherAmount(newProduct), NewIOUEitherAmount(oneAmt))
	return WithinRelativeDistance(productQ, newProductQ, 1e-7)
}

// Send transfers amounts through the AMM using accountSend, waiving transfer fees.
// Reference: rippled AMMOffer.h send() — delegates to accountSend with WaiveTransferFee
func (o *AMMOffer) Send(sb *PaymentSandbox, from, to [20]byte, amount tx.Amount) error {
	if amount.IsZero() {
		return nil
	}
	if amount.IsNative() {
		return xrpTransferInSandbox(sb, from, to, amount.Drops())
	}
	return iouTransferInSandbox(sb, from, to, amount)
}

// xrpTransferInSandbox transfers XRP drops between accounts in a sandbox.
// When from or to is the zero account (XRP pseudo-account), that side is skipped.
// Reference: rippled View.cpp accountSend() lines 1888-1939
func xrpTransferInSandbox(sb *PaymentSandbox, from, to [20]byte, drops int64) error {
	if drops == 0 {
		return nil
	}

	var zeroAccount [20]byte
	txHash, ledgerSeq := sb.GetTransactionContext()

	// Debit source (skip if zero account — XRPEndpointStep handles actual source)
	if from != zeroAccount {
		fromKey := keylet.Account(from)
		fromData, err := sb.Read(fromKey)
		if err != nil || fromData == nil {
			return errors.New("source account not found")
		}
		fromAcct, err := state.ParseAccountRoot(fromData)
		if err != nil {
			return err
		}
		fromAcct.Balance = fromAcct.Balance - uint64(drops)
		fromAcct.PreviousTxnID = txHash
		fromAcct.PreviousTxnLgrSeq = ledgerSeq
		newFromData, _ := state.SerializeAccountRoot(fromAcct)
		sb.Update(fromKey, newFromData)
	}

	// Credit destination (skip if zero account — XRPEndpointStep handles actual dest)
	if to != zeroAccount {
		toKey := keylet.Account(to)
		toData, err := sb.Read(toKey)
		if err != nil || toData == nil {
			return errors.New("destination account not found")
		}
		toAcct, err := state.ParseAccountRoot(toData)
		if err != nil {
			return err
		}
		toAcct.Balance = toAcct.Balance + uint64(drops)
		toAcct.PreviousTxnID = txHash
		toAcct.PreviousTxnLgrSeq = ledgerSeq
		newToData, _ := state.SerializeAccountRoot(toAcct)
		sb.Update(toKey, newToData)
	}

	return nil
}

// iouTransferInSandbox transfers IOU between accounts via trust line updates.
func iouTransferInSandbox(sb *PaymentSandbox, from, to [20]byte, amount tx.Amount) error {
	if amount.IsZero() || amount.IsNative() {
		return nil
	}

	issuerID, err := state.DecodeAccountID(amount.Issuer)
	if err != nil {
		return err
	}

	if from == issuerID {
		// Issuer sends: credit receiver's trust line
		return adjustTrustLineBalance(sb, to, issuerID, amount.Currency, amount, true)
	}
	if to == issuerID {
		// Send to issuer: debit sender's trust line
		return adjustTrustLineBalance(sb, from, issuerID, amount.Currency, amount, false)
	}

	// Through issuer: debit sender, credit receiver
	if err := adjustTrustLineBalance(sb, from, issuerID, amount.Currency, amount, false); err != nil {
		return err
	}
	return adjustTrustLineBalance(sb, to, issuerID, amount.Currency, amount, true)
}

// adjustTrustLineBalance adjusts a trust line balance.
// If credit=true, adds amount to account's balance; if credit=false, subtracts.
func adjustTrustLineBalance(sb *PaymentSandbox, account, issuer [20]byte, currency string, amount tx.Amount, credit bool) error {
	tlKey := keylet.Line(account, issuer, currency)
	data, err := sb.Read(tlKey)
	if err != nil || data == nil {
		return errors.New("trust line not found")
	}

	tl, err := state.ParseRippleState(data)
	if err != nil {
		return err
	}

	lowID, _ := state.DecodeAccountID(tl.LowLimit.Issuer)
	isLow := lowID == account

	if isLow {
		if credit {
			tl.Balance, _ = tl.Balance.Add(amount)
		} else {
			tl.Balance, _ = tl.Balance.Sub(amount)
		}
	} else {
		// High account: balance is inverted
		if credit {
			tl.Balance, _ = tl.Balance.Sub(amount)
		} else {
			tl.Balance, _ = tl.Balance.Add(amount)
		}
	}

	txHash, ledgerSeq := sb.GetTransactionContext()
	tl.PreviousTxnID = txHash
	tl.PreviousTxnLgrSeq = ledgerSeq

	newData, err := state.SerializeRippleState(tl)
	if err != nil {
		return err
	}
	sb.Update(tlKey, newData)
	return nil
}

// eitherToAmount converts an EitherAmount back to a tx.Amount.
func eitherToAmount(ea EitherAmount) tx.Amount {
	if ea.IsNative {
		return state.NewXRPAmountFromInt(ea.XRP)
	}
	return ea.IOU
}
