// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/peermanagement/proto/ripple.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message types for the XRPL peer protocol
type MessageType int32

const (
	MessageType_mtUNKNOWN                 MessageType = 0
	MessageType_mtMANIFESTS               MessageType = 2
	MessageType_mtPING                    MessageType = 3
	MessageType_mtCLUSTER                 MessageType = 5
	MessageType_mtENDPOINTS               MessageType = 15
	MessageType_mtTRANSACTION             MessageType = 30
	MessageType_mtGET_LEDGER              MessageType = 31
	MessageType_mtLEDGER_DATA             MessageType = 32
	MessageType_mtPROPOSE_LEDGER          MessageType = 33
	MessageType_mtSTATUS_CHANGE           MessageType = 34
	MessageType_mtHAVE_SET                MessageType = 35
	MessageType_mtVALIDATION              MessageType = 41
	MessageType_mtGET_OBJECTS             MessageType = 42
	MessageType_mtVALIDATORLIST           MessageType = 54
	MessageType_mtSQUELCH                 MessageType = 55
	MessageType_mtVALIDATORLISTCOLLECTION MessageType = 56
	MessageType_mtPROOF_PATH_REQ          MessageType = 57
	MessageType_mtPROOF_PATH_RESPONSE     MessageType = 58
	MessageType_mtREPLAY_DELTA_REQ        MessageType = 59
	MessageType_mtREPLAY_DELTA_RESPONSE   MessageType = 60
	MessageType_mtHAVE_TRANSACTIONS       MessageType = 63
	MessageType_mtTRANSACTIONS            MessageType = 64
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "mtUNKNOWN",
		2:  "mtMANIFESTS",
		3:  "mtPING",
		5:  "mtCLUSTER",
		15: "mtENDPOINTS",
		30: "mtTRANSACTION",
		31: "mtGET_LEDGER",
		32: "mtLEDGER_DATA",
		33: "mtPROPOSE_LEDGER",
		34: "mtSTATUS_CHANGE",
		35: "mtHAVE_SET",
		41: "mtVALIDATION",
		42: "mtGET_OBJECTS",
		54: "mtVALIDATORLIST",
		55: "mtSQUELCH",
		56: "mtVALIDATORLISTCOLLECTION",
		57: "mtPROOF_PATH_REQ",
		58: "mtPROOF_PATH_RESPONSE",
		59: "mtREPLAY_DELTA_REQ",
		60: "mtREPLAY_DELTA_RESPONSE",
		63: "mtHAVE_TRANSACTIONS",
		64: "mtTRANSACTIONS",
	}
	MessageType_value = map[string]int32{
		"mtUNKNOWN":                 0,
		"mtMANIFESTS":               2,
		"mtPING":                    3,
		"mtCLUSTER":                 5,
		"mtENDPOINTS":               15,
		"mtTRANSACTION":             30,
		"mtGET_LEDGER":              31,
		"mtLEDGER_DATA":             32,
		"mtPROPOSE_LEDGER":          33,
		"mtSTATUS_CHANGE":           34,
		"mtHAVE_SET":                35,
		"mtVALIDATION":              41,
		"mtGET_OBJECTS":             42,
		"mtVALIDATORLIST":           54,
		"mtSQUELCH":                 55,
		"mtVALIDATORLISTCOLLECTION": 56,
		"mtPROOF_PATH_REQ":          57,
		"mtPROOF_PATH_RESPONSE":     58,
		"mtREPLAY_DELTA_REQ":        59,
		"mtREPLAY_DELTA_RESPONSE":   60,
		"mtHAVE_TRANSACTIONS":       63,
		"mtTRANSACTIONS":            64,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{0}
}

// Transaction status
type TransactionStatus int32

const (
	TransactionStatus_tsUNKNOWN         TransactionStatus = 0
	TransactionStatus_tsNEW             TransactionStatus = 1
	TransactionStatus_tsCURRENT         TransactionStatus = 2
	TransactionStatus_tsCOMMITED        TransactionStatus = 3
	TransactionStatus_tsREJECT_CONFLICT TransactionStatus = 4
	TransactionStatus_tsREJECT_INVALID  TransactionStatus = 5
	TransactionStatus_tsREJECT_FUNDS    TransactionStatus = 6
	TransactionStatus_tsHELD_SEQ        TransactionStatus = 7
	TransactionStatus_tsHELD_LEDGER     TransactionStatus = 8
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "tsUNKNOWN",
		1: "tsNEW",
		2: "tsCURRENT",
		3: "tsCOMMITED",
		4: "tsREJECT_CONFLICT",
		5: "tsREJECT_INVALID",
		6: "tsREJECT_FUNDS",
		7: "tsHELD_SEQ",
		8: "tsHELD_LEDGER",
	}
	TransactionStatus_value = map[string]int32{
		"tsUNKNOWN":         0,
		"tsNEW":             1,
		"tsCURRENT":         2,
		"tsCOMMITED":        3,
		"tsREJECT_CONFLICT": 4,
		"tsREJECT_INVALID":  5,
		"tsREJECT_FUNDS":    6,
		"tsHELD_SEQ":        7,
		"tsHELD_LEDGER":     8,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[1].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[1]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{1}
}

// Node status
type NodeStatus int32

const (
	NodeStatus_nsUNKNOWN    NodeStatus = 0
	NodeStatus_nsCONNECTING NodeStatus = 1
	NodeStatus_nsCONNECTED  NodeStatus = 2
	NodeStatus_nsMONITORING NodeStatus = 3
	NodeStatus_nsVALIDATING NodeStatus = 4
	NodeStatus_nsSHUTTING   NodeStatus = 5
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "nsUNKNOWN",
		1: "nsCONNECTING",
		2: "nsCONNECTED",
		3: "nsMONITORING",
		4: "nsVALIDATING",
		5: "nsSHUTTING",
	}
	NodeStatus_value = map[string]int32{
		"nsUNKNOWN":    0,
		"nsCONNECTING": 1,
		"nsCONNECTED":  2,
		"nsMONITORING": 3,
		"nsVALIDATING": 4,
		"nsSHUTTING":   5,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[2].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[2]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{2}
}

// Node events
type NodeEvent int32

const (
	NodeEvent_neUNKNOWN         NodeEvent = 0
	NodeEvent_neCLOSING_LEDGER  NodeEvent = 1
	NodeEvent_neACCEPTED_LEDGER NodeEvent = 2
	NodeEvent_neSWITCHED_LEDGER NodeEvent = 3
	NodeEvent_neLOST_SYNC       NodeEvent = 4
)

// Enum value maps for NodeEvent.
var (
	NodeEvent_name = map[int32]string{
		0: "neUNKNOWN",
		1: "neCLOSING_LEDGER",
		2: "neACCEPTED_LEDGER",
		3: "neSWITCHED_LEDGER",
		4: "neLOST_SYNC",
	}
	NodeEvent_value = map[string]int32{
		"neUNKNOWN":         0,
		"neCLOSING_LEDGER":  1,
		"neACCEPTED_LEDGER": 2,
		"neSWITCHED_LEDGER": 3,
		"neLOST_SYNC":       4,
	}
)

func (x NodeEvent) Enum() *NodeEvent {
	p := new(NodeEvent)
	*p = x
	return p
}

func (x NodeEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[3].Descriptor()
}

func (NodeEvent) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[3]
}

func (x NodeEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeEvent.Descriptor instead.
func (NodeEvent) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{3}
}

// Transaction set status
type TxSetStatus int32

const (
	TxSetStatus_tsUNKNOWN_SET TxSetStatus = 0
	TxSetStatus_tsHAVE        TxSetStatus = 1
	TxSetStatus_tsCAN_GET     TxSetStatus = 2
	TxSetStatus_tsNEED        TxSetStatus = 3
)

// Enum value maps for TxSetStatus.
var (
	TxSetStatus_name = map[int32]string{
		0: "tsUNKNOWN_SET",
		1: "tsHAVE",
		2: "tsCAN_GET",
		3: "tsNEED",
	}
	TxSetStatus_value = map[string]int32{
		"tsUNKNOWN_SET": 0,
		"tsHAVE":        1,
		"tsCAN_GET":     2,
		"tsNEED":        3,
	}
)

func (x TxSetStatus) Enum() *TxSetStatus {
	p := new(TxSetStatus)
	*p = x
	return p
}

func (x TxSetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxSetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[4].Descriptor()
}

func (TxSetStatus) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[4]
}

func (x TxSetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxSetStatus.Descriptor instead.
func (TxSetStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{4}
}

// Object types
type ObjectType int32

const (
	ObjectType_otUNKNOWN          ObjectType = 0
	ObjectType_otLEDGER           ObjectType = 1
	ObjectType_otTRANSACTION      ObjectType = 2
	ObjectType_otTRANSACTION_NODE ObjectType = 3
	ObjectType_otSTATE_NODE       ObjectType = 4
	ObjectType_otCAS_OBJECT       ObjectType = 5
	ObjectType_otFETCH_PACK       ObjectType = 6
	ObjectType_otTRANSACTIONS     ObjectType = 7
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "otUNKNOWN",
		1: "otLEDGER",
		2: "otTRANSACTION",
		3: "otTRANSACTION_NODE",
		4: "otSTATE_NODE",
		5: "otCAS_OBJECT",
		6: "otFETCH_PACK",
		7: "otTRANSACTIONS",
	}
	ObjectType_value = map[string]int32{
		"otUNKNOWN":          0,
		"otLEDGER":           1,
		"otTRANSACTION":      2,
		"otTRANSACTION_NODE": 3,
		"otSTATE_NODE":       4,
		"otCAS_OBJECT":       5,
		"otFETCH_PACK":       6,
		"otTRANSACTIONS":     7,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[5].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[5]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{5}
}

// Ledger info types
type TMLedgerInfoType int32

const (
	TMLedgerInfoType_liBASE         TMLedgerInfoType = 0
	TMLedgerInfoType_liTX_NODE      TMLedgerInfoType = 1
	TMLedgerInfoType_liAS_NODE      TMLedgerInfoType = 2
	TMLedgerInfoType_liTS_CANDIDATE TMLedgerInfoType = 3
)

// Enum value maps for TMLedgerInfoType.
var (
	TMLedgerInfoType_name = map[int32]string{
		0: "liBASE",
		1: "liTX_NODE",
		2: "liAS_NODE",
		3: "liTS_CANDIDATE",
	}
	TMLedgerInfoType_value = map[string]int32{
		"liBASE":         0,
		"liTX_NODE":      1,
		"liAS_NODE":      2,
		"liTS_CANDIDATE": 3,
	}
)

func (x TMLedgerInfoType) Enum() *TMLedgerInfoType {
	p := new(TMLedgerInfoType)
	*p = x
	return p
}

func (x TMLedgerInfoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TMLedgerInfoType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[6].Descriptor()
}

func (TMLedgerInfoType) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[6]
}

func (x TMLedgerInfoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TMLedgerInfoType.Descriptor instead.
func (TMLedgerInfoType) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{6}
}

// Ledger types
type TMLedgerType int32

const (
	TMLedgerType_ltACCEPTED TMLedgerType = 0
	TMLedgerType_ltCURRENT  TMLedgerType = 1
	TMLedgerType_ltCLOSED   TMLedgerType = 2
)

// Enum value maps for TMLedgerType.
var (
	TMLedgerType_name = map[int32]string{
		0: "ltACCEPTED",
		1: "ltCURRENT",
		2: "ltCLOSED",
	}
	TMLedgerType_value = map[string]int32{
		"ltACCEPTED": 0,
		"ltCURRENT":  1,
		"ltCLOSED":   2,
	}
)

func (x TMLedgerType) Enum() *TMLedgerType {
	p := new(TMLedgerType)
	*p = x
	return p
}

func (x TMLedgerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TMLedgerType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[7].Descriptor()
}

func (TMLedgerType) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[7]
}

func (x TMLedgerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TMLedgerType.Descriptor instead.
func (TMLedgerType) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{7}
}

// Query type
type TMQueryType int32

const (
	TMQueryType_qtINDIRECT TMQueryType = 0
)

// Enum value maps for TMQueryType.
var (
	TMQueryType_name = map[int32]string{
		0: "qtINDIRECT",
	}
	TMQueryType_value = map[string]int32{
		"qtINDIRECT": 0,
	}
)

func (x TMQueryType) Enum() *TMQueryType {
	p := new(TMQueryType)
	*p = x
	return p
}

func (x TMQueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TMQueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[8].Descriptor()
}

func (TMQueryType) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[8]
}

func (x TMQueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TMQueryType.Descriptor instead.
func (TMQueryType) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{8}
}

// Reply errors
type TMReplyError int32

const (
	TMReplyError_reNO_ERROR    TMReplyError = 0
	TMReplyError_reNO_LEDGER   TMReplyError = 1
	TMReplyError_reNO_NODE     TMReplyError = 2
	TMReplyError_reBAD_REQUEST TMReplyError = 3
)

// Enum value maps for TMReplyError.
var (
	TMReplyError_name = map[int32]string{
		0: "reNO_ERROR",
		1: "reNO_LEDGER",
		2: "reNO_NODE",
		3: "reBAD_REQUEST",
	}
	TMReplyError_value = map[string]int32{
		"reNO_ERROR":    0,
		"reNO_LEDGER":   1,
		"reNO_NODE":     2,
		"reBAD_REQUEST": 3,
	}
)

func (x TMReplyError) Enum() *TMReplyError {
	p := new(TMReplyError)
	*p = x
	return p
}

func (x TMReplyError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TMReplyError) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[9].Descriptor()
}

func (TMReplyError) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[9]
}

func (x TMReplyError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TMReplyError.Descriptor instead.
func (TMReplyError) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{9}
}

// Ledger map types
type TMLedgerMapType int32

const (
	TMLedgerMapType_lmUNKNOWN       TMLedgerMapType = 0
	TMLedgerMapType_lmTRANSACTION   TMLedgerMapType = 1
	TMLedgerMapType_lmACCOUNT_STATE TMLedgerMapType = 2
)

// Enum value maps for TMLedgerMapType.
var (
	TMLedgerMapType_name = map[int32]string{
		0: "lmUNKNOWN",
		1: "lmTRANSACTION",
		2: "lmACCOUNT_STATE",
	}
	TMLedgerMapType_value = map[string]int32{
		"lmUNKNOWN":       0,
		"lmTRANSACTION":   1,
		"lmACCOUNT_STATE": 2,
	}
)

func (x TMLedgerMapType) Enum() *TMLedgerMapType {
	p := new(TMLedgerMapType)
	*p = x
	return p
}

func (x TMLedgerMapType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TMLedgerMapType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[10].Descriptor()
}

func (TMLedgerMapType) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[10]
}

func (x TMLedgerMapType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TMLedgerMapType.Descriptor instead.
func (TMLedgerMapType) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{10}
}

type TMPing_PingType int32

const (
	TMPing_ptPING TMPing_PingType = 0
	TMPing_ptPONG TMPing_PingType = 1
)

// Enum value maps for TMPing_PingType.
var (
	TMPing_PingType_name = map[int32]string{
		0: "ptPING",
		1: "ptPONG",
	}
	TMPing_PingType_value = map[string]int32{
		"ptPING": 0,
		"ptPONG": 1,
	}
)

func (x TMPing_PingType) Enum() *TMPing_PingType {
	p := new(TMPing_PingType)
	*p = x
	return p
}

func (x TMPing_PingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TMPing_PingType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_peermanagement_proto_ripple_proto_enumTypes[11].Descriptor()
}

func (TMPing_PingType) Type() protoreflect.EnumType {
	return &file_internal_peermanagement_proto_ripple_proto_enumTypes[11]
}

func (x TMPing_PingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TMPing_PingType.Descriptor instead.
func (TMPing_PingType) EnumDescriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{21, 0}
}

// Provides the current ephemeral key for a validator
type TMManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stobject      []byte                 `protobuf:"bytes,1,opt,name=stobject,proto3" json:"stobject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMManifest) Reset() {
	*x = TMManifest{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMManifest) ProtoMessage() {}

func (x *TMManifest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMManifest.ProtoReflect.Descriptor instead.
func (*TMManifest) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{0}
}

func (x *TMManifest) GetStobject() []byte {
	if x != nil {
		return x.Stobject
	}
	return nil
}

type TMManifests struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	List  []*TMManifest          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
	History       bool `protobuf:"varint,2,opt,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMManifests) Reset() {
	*x = TMManifests{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMManifests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMManifests) ProtoMessage() {}

func (x *TMManifests) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMManifests.ProtoReflect.Descriptor instead.
func (*TMManifests) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{1}
}

func (x *TMManifests) GetList() []*TMManifest {
	if x != nil {
		return x.List
	}
	return nil
}

// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
func (x *TMManifests) GetHistory() bool {
	if x != nil {
		return x.History
	}
	return false
}

// Cluster node status
type TMClusterNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ReportTime    uint32                 `protobuf:"varint,2,opt,name=report_time,json=reportTime,proto3" json:"report_time,omitempty"`
	NodeLoad      uint32                 `protobuf:"varint,3,opt,name=node_load,json=nodeLoad,proto3" json:"node_load,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMClusterNode) Reset() {
	*x = TMClusterNode{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMClusterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMClusterNode) ProtoMessage() {}

func (x *TMClusterNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMClusterNode.ProtoReflect.Descriptor instead.
func (*TMClusterNode) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{2}
}

func (x *TMClusterNode) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *TMClusterNode) GetReportTime() uint32 {
	if x != nil {
		return x.ReportTime
	}
	return 0
}

func (x *TMClusterNode) GetNodeLoad() uint32 {
	if x != nil {
		return x.NodeLoad
	}
	return 0
}

func (x *TMClusterNode) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TMClusterNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Load sources
type TMLoadSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cost          uint32                 `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMLoadSource) Reset() {
	*x = TMLoadSource{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMLoadSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMLoadSource) ProtoMessage() {}

func (x *TMLoadSource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMLoadSource.ProtoReflect.Descriptor instead.
func (*TMLoadSource) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{3}
}

func (x *TMLoadSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TMLoadSource) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *TMLoadSource) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Cluster status
type TMCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterNodes  []*TMClusterNode       `protobuf:"bytes,1,rep,name=cluster_nodes,json=clusterNodes,proto3" json:"cluster_nodes,omitempty"`
	LoadSources   []*TMLoadSource        `protobuf:"bytes,2,rep,name=load_sources,json=loadSources,proto3" json:"load_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMCluster) Reset() {
	*x = TMCluster{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMCluster) ProtoMessage() {}

func (x *TMCluster) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMCluster.ProtoReflect.Descriptor instead.
func (*TMCluster) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{4}
}

func (x *TMCluster) GetClusterNodes() []*TMClusterNode {
	if x != nil {
		return x.ClusterNodes
	}
	return nil
}

func (x *TMCluster) GetLoadSources() []*TMLoadSource {
	if x != nil {
		return x.LoadSources
	}
	return nil
}

// Public key
type TMPublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMPublicKey) Reset() {
	*x = TMPublicKey{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMPublicKey) ProtoMessage() {}

func (x *TMPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMPublicKey.ProtoReflect.Descriptor instead.
func (*TMPublicKey) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{5}
}

func (x *TMPublicKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type TMTransaction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RawTransaction   []byte                 `protobuf:"bytes,1,opt,name=raw_transaction,json=rawTransaction,proto3" json:"raw_transaction,omitempty"`
	Status           TransactionStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=protocol.TransactionStatus" json:"status,omitempty"`
	ReceiveTimestamp uint64                 `protobuf:"varint,3,opt,name=receive_timestamp,json=receiveTimestamp,proto3" json:"receive_timestamp,omitempty"`
	Deferred         bool                   `protobuf:"varint,4,opt,name=deferred,proto3" json:"deferred,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TMTransaction) Reset() {
	*x = TMTransaction{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMTransaction) ProtoMessage() {}

func (x *TMTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMTransaction.ProtoReflect.Descriptor instead.
func (*TMTransaction) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{6}
}

func (x *TMTransaction) GetRawTransaction() []byte {
	if x != nil {
		return x.RawTransaction
	}
	return nil
}

func (x *TMTransaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_tsUNKNOWN
}

func (x *TMTransaction) GetReceiveTimestamp() uint64 {
	if x != nil {
		return x.ReceiveTimestamp
	}
	return 0
}

func (x *TMTransaction) GetDeferred() bool {
	if x != nil {
		return x.Deferred
	}
	return false
}

type TMTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TMTransaction       `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMTransactions) Reset() {
	*x = TMTransactions{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMTransactions) ProtoMessage() {}

func (x *TMTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMTransactions.ProtoReflect.Descriptor instead.
func (*TMTransactions) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{7}
}

func (x *TMTransactions) GetTransactions() []*TMTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TMStatusChange struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NewStatus          NodeStatus             `protobuf:"varint,1,opt,name=new_status,json=newStatus,proto3,enum=protocol.NodeStatus" json:"new_status,omitempty"`
	NewEvent           NodeEvent              `protobuf:"varint,2,opt,name=new_event,json=newEvent,proto3,enum=protocol.NodeEvent" json:"new_event,omitempty"`
	LedgerSeq          uint32                 `protobuf:"varint,3,opt,name=ledger_seq,json=ledgerSeq,proto3" json:"ledger_seq,omitempty"`
	LedgerHash         []byte                 `protobuf:"bytes,4,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	LedgerHashPrevious []byte                 `protobuf:"bytes,5,opt,name=ledger_hash_previous,json=ledgerHashPrevious,proto3" json:"ledger_hash_previous,omitempty"`
	NetworkTime        uint64                 `protobuf:"varint,6,opt,name=network_time,json=networkTime,proto3" json:"network_time,omitempty"`
	FirstSeq           uint32                 `protobuf:"varint,7,opt,name=first_seq,json=firstSeq,proto3" json:"first_seq,omitempty"`
	LastSeq            uint32                 `protobuf:"varint,8,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TMStatusChange) Reset() {
	*x = TMStatusChange{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMStatusChange) ProtoMessage() {}

func (x *TMStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMStatusChange.ProtoReflect.Descriptor instead.
func (*TMStatusChange) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{8}
}

func (x *TMStatusChange) GetNewStatus() NodeStatus {
	if x != nil {
		return x.NewStatus
	}
	return NodeStatus_nsUNKNOWN
}

func (x *TMStatusChange) GetNewEvent() NodeEvent {
	if x != nil {
		return x.NewEvent
	}
	return NodeEvent_neUNKNOWN
}

func (x *TMStatusChange) GetLedgerSeq() uint32 {
	if x != nil {
		return x.LedgerSeq
	}
	return 0
}

func (x *TMStatusChange) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

func (x *TMStatusChange) GetLedgerHashPrevious() []byte {
	if x != nil {
		return x.LedgerHashPrevious
	}
	return nil
}

func (x *TMStatusChange) GetNetworkTime() uint64 {
	if x != nil {
		return x.NetworkTime
	}
	return 0
}

func (x *TMStatusChange) GetFirstSeq() uint32 {
	if x != nil {
		return x.FirstSeq
	}
	return 0
}

func (x *TMStatusChange) GetLastSeq() uint32 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

// Ledger proposal
type TMProposeSet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProposeSeq     uint32                 `protobuf:"varint,1,opt,name=propose_seq,json=proposeSeq,proto3" json:"propose_seq,omitempty"`
	CurrentTxHash  []byte                 `protobuf:"bytes,2,opt,name=current_tx_hash,json=currentTxHash,proto3" json:"current_tx_hash,omitempty"`
	NodePubKey     []byte                 `protobuf:"bytes,3,opt,name=node_pub_key,json=nodePubKey,proto3" json:"node_pub_key,omitempty"`
	CloseTime      uint32                 `protobuf:"varint,4,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	PreviousLedger []byte                 `protobuf:"bytes,6,opt,name=previous_ledger,json=previousLedger,proto3" json:"previous_ledger,omitempty"`
	// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
	CheckedSignature    bool     `protobuf:"varint,7,opt,name=checked_signature,json=checkedSignature,proto3" json:"checked_signature,omitempty"`
	AddedTransactions   [][]byte `protobuf:"bytes,10,rep,name=added_transactions,json=addedTransactions,proto3" json:"added_transactions,omitempty"`
	RemovedTransactions [][]byte `protobuf:"bytes,11,rep,name=removed_transactions,json=removedTransactions,proto3" json:"removed_transactions,omitempty"`
	// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
	Hops          uint32 `protobuf:"varint,12,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMProposeSet) Reset() {
	*x = TMProposeSet{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMProposeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMProposeSet) ProtoMessage() {}

func (x *TMProposeSet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMProposeSet.ProtoReflect.Descriptor instead.
func (*TMProposeSet) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{9}
}

func (x *TMProposeSet) GetProposeSeq() uint32 {
	if x != nil {
		return x.ProposeSeq
	}
	return 0
}

func (x *TMProposeSet) GetCurrentTxHash() []byte {
	if x != nil {
		return x.CurrentTxHash
	}
	return nil
}

func (x *TMProposeSet) GetNodePubKey() []byte {
	if x != nil {
		return x.NodePubKey
	}
	return nil
}

func (x *TMProposeSet) GetCloseTime() uint32 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

func (x *TMProposeSet) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TMProposeSet) GetPreviousLedger() []byte {
	if x != nil {
		return x.PreviousLedger
	}
	return nil
}

// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
func (x *TMProposeSet) GetCheckedSignature() bool {
	if x != nil {
		return x.CheckedSignature
	}
	return false
}

func (x *TMProposeSet) GetAddedTransactions() [][]byte {
	if x != nil {
		return x.AddedTransactions
	}
	return nil
}

func (x *TMProposeSet) GetRemovedTransactions() [][]byte {
	if x != nil {
		return x.RemovedTransactions
	}
	return nil
}

// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
func (x *TMProposeSet) GetHops() uint32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

type TMHaveTransactionSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TxSetStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=protocol.TxSetStatus" json:"status,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMHaveTransactionSet) Reset() {
	*x = TMHaveTransactionSet{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMHaveTransactionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMHaveTransactionSet) ProtoMessage() {}

func (x *TMHaveTransactionSet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMHaveTransactionSet.ProtoReflect.Descriptor instead.
func (*TMHaveTransactionSet) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{10}
}

func (x *TMHaveTransactionSet) GetStatus() TxSetStatus {
	if x != nil {
		return x.Status
	}
	return TxSetStatus_tsUNKNOWN_SET
}

func (x *TMHaveTransactionSet) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Validator list
type TMValidatorList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Blob          []byte                 `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Version       uint32                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMValidatorList) Reset() {
	*x = TMValidatorList{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMValidatorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMValidatorList) ProtoMessage() {}

func (x *TMValidatorList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMValidatorList.ProtoReflect.Descriptor instead.
func (*TMValidatorList) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{11}
}

func (x *TMValidatorList) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *TMValidatorList) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *TMValidatorList) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TMValidatorList) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Validator list v2
type ValidatorBlobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Blob          []byte                 `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorBlobInfo) Reset() {
	*x = ValidatorBlobInfo{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorBlobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorBlobInfo) ProtoMessage() {}

func (x *ValidatorBlobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorBlobInfo.ProtoReflect.Descriptor instead.
func (*ValidatorBlobInfo) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{12}
}

func (x *ValidatorBlobInfo) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *ValidatorBlobInfo) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *ValidatorBlobInfo) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TMValidatorListCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Manifest      []byte                 `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Blobs         []*ValidatorBlobInfo   `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMValidatorListCollection) Reset() {
	*x = TMValidatorListCollection{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMValidatorListCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMValidatorListCollection) ProtoMessage() {}

func (x *TMValidatorListCollection) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMValidatorListCollection.ProtoReflect.Descriptor instead.
func (*TMValidatorListCollection) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{13}
}

func (x *TMValidatorListCollection) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TMValidatorListCollection) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *TMValidatorListCollection) GetBlobs() []*ValidatorBlobInfo {
	if x != nil {
		return x.Blobs
	}
	return nil
}

// Validation message
type TMValidation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Validation []byte                 `protobuf:"bytes,1,opt,name=validation,proto3" json:"validation,omitempty"`
	// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
	CheckedSignature bool `protobuf:"varint,2,opt,name=checked_signature,json=checkedSignature,proto3" json:"checked_signature,omitempty"`
	// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
	Hops          uint32 `protobuf:"varint,3,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMValidation) Reset() {
	*x = TMValidation{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMValidation) ProtoMessage() {}

func (x *TMValidation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMValidation.ProtoReflect.Descriptor instead.
func (*TMValidation) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{14}
}

func (x *TMValidation) GetValidation() []byte {
	if x != nil {
		return x.Validation
	}
	return nil
}

// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
func (x *TMValidation) GetCheckedSignature() bool {
	if x != nil {
		return x.CheckedSignature
	}
	return false
}

// Deprecated: Marked as deprecated in internal/peermanagement/proto/ripple.proto.
func (x *TMValidation) GetHops() uint32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

// Endpoints for peer discovery
type TMEndpoints struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Version       uint32                      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EndpointsV2   []*TMEndpoints_TMEndpointv2 `protobuf:"bytes,3,rep,name=endpoints_v2,json=endpointsV2,proto3" json:"endpoints_v2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMEndpoints) Reset() {
	*x = TMEndpoints{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMEndpoints) ProtoMessage() {}

func (x *TMEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMEndpoints.ProtoReflect.Descriptor instead.
func (*TMEndpoints) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{15}
}

func (x *TMEndpoints) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TMEndpoints) GetEndpointsV2() []*TMEndpoints_TMEndpointv2 {
	if x != nil {
		return x.EndpointsV2
	}
	return nil
}

// Indexed object
type TMIndexedObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Index         []byte                 `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	LedgerSeq     uint32                 `protobuf:"varint,5,opt,name=ledger_seq,json=ledgerSeq,proto3" json:"ledger_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMIndexedObject) Reset() {
	*x = TMIndexedObject{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMIndexedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMIndexedObject) ProtoMessage() {}

func (x *TMIndexedObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMIndexedObject.ProtoReflect.Descriptor instead.
func (*TMIndexedObject) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{16}
}

func (x *TMIndexedObject) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *TMIndexedObject) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *TMIndexedObject) GetIndex() []byte {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *TMIndexedObject) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TMIndexedObject) GetLedgerSeq() uint32 {
	if x != nil {
		return x.LedgerSeq
	}
	return 0
}

type TMGetObjectByHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ObjectType             `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.ObjectType" json:"type,omitempty"`
	Query         bool                   `protobuf:"varint,2,opt,name=query,proto3" json:"query,omitempty"`
	Seq           uint32                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	LedgerHash    []byte                 `protobuf:"bytes,4,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	Fat           bool                   `protobuf:"varint,5,opt,name=fat,proto3" json:"fat,omitempty"`
	Objects       []*TMIndexedObject     `protobuf:"bytes,6,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMGetObjectByHash) Reset() {
	*x = TMGetObjectByHash{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMGetObjectByHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMGetObjectByHash) ProtoMessage() {}

func (x *TMGetObjectByHash) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMGetObjectByHash.ProtoReflect.Descriptor instead.
func (*TMGetObjectByHash) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{17}
}

func (x *TMGetObjectByHash) GetType() ObjectType {
	if x != nil {
		return x.Type
	}
	return ObjectType_otUNKNOWN
}

func (x *TMGetObjectByHash) GetQuery() bool {
	if x != nil {
		return x.Query
	}
	return false
}

func (x *TMGetObjectByHash) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TMGetObjectByHash) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

func (x *TMGetObjectByHash) GetFat() bool {
	if x != nil {
		return x.Fat
	}
	return false
}

func (x *TMGetObjectByHash) GetObjects() []*TMIndexedObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

// Ledger node
type TMLedgerNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodedata      []byte                 `protobuf:"bytes,1,opt,name=nodedata,proto3" json:"nodedata,omitempty"`
	Nodeid        []byte                 `protobuf:"bytes,2,opt,name=nodeid,proto3" json:"nodeid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMLedgerNode) Reset() {
	*x = TMLedgerNode{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMLedgerNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMLedgerNode) ProtoMessage() {}

func (x *TMLedgerNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMLedgerNode.ProtoReflect.Descriptor instead.
func (*TMLedgerNode) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{18}
}

func (x *TMLedgerNode) GetNodedata() []byte {
	if x != nil {
		return x.Nodedata
	}
	return nil
}

func (x *TMLedgerNode) GetNodeid() []byte {
	if x != nil {
		return x.Nodeid
	}
	return nil
}

type TMGetLedger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Itype         TMLedgerInfoType       `protobuf:"varint,1,opt,name=itype,proto3,enum=protocol.TMLedgerInfoType" json:"itype,omitempty"`
	Ltype         TMLedgerType           `protobuf:"varint,2,opt,name=ltype,proto3,enum=protocol.TMLedgerType" json:"ltype,omitempty"`
	LedgerHash    []byte                 `protobuf:"bytes,3,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	LedgerSeq     uint32                 `protobuf:"varint,4,opt,name=ledger_seq,json=ledgerSeq,proto3" json:"ledger_seq,omitempty"`
	NodeIds       [][]byte               `protobuf:"bytes,5,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	RequestCookie uint64                 `protobuf:"varint,6,opt,name=request_cookie,json=requestCookie,proto3" json:"request_cookie,omitempty"`
	QueryType     TMQueryType            `protobuf:"varint,7,opt,name=query_type,json=queryType,proto3,enum=protocol.TMQueryType" json:"query_type,omitempty"`
	QueryDepth    uint32                 `protobuf:"varint,8,opt,name=query_depth,json=queryDepth,proto3" json:"query_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMGetLedger) Reset() {
	*x = TMGetLedger{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMGetLedger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMGetLedger) ProtoMessage() {}

func (x *TMGetLedger) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMGetLedger.ProtoReflect.Descriptor instead.
func (*TMGetLedger) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{19}
}

func (x *TMGetLedger) GetItype() TMLedgerInfoType {
	if x != nil {
		return x.Itype
	}
	return TMLedgerInfoType_liBASE
}

func (x *TMGetLedger) GetLtype() TMLedgerType {
	if x != nil {
		return x.Ltype
	}
	return TMLedgerType_ltACCEPTED
}

func (x *TMGetLedger) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

func (x *TMGetLedger) GetLedgerSeq() uint32 {
	if x != nil {
		return x.LedgerSeq
	}
	return 0
}

func (x *TMGetLedger) GetNodeIds() [][]byte {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *TMGetLedger) GetRequestCookie() uint64 {
	if x != nil {
		return x.RequestCookie
	}
	return 0
}

func (x *TMGetLedger) GetQueryType() TMQueryType {
	if x != nil {
		return x.QueryType
	}
	return TMQueryType_qtINDIRECT
}

func (x *TMGetLedger) GetQueryDepth() uint32 {
	if x != nil {
		return x.QueryDepth
	}
	return 0
}

type TMLedgerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerHash    []byte                 `protobuf:"bytes,1,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	LedgerSeq     uint32                 `protobuf:"varint,2,opt,name=ledger_seq,json=ledgerSeq,proto3" json:"ledger_seq,omitempty"`
	Type          TMLedgerInfoType       `protobuf:"varint,3,opt,name=type,proto3,enum=protocol.TMLedgerInfoType" json:"type,omitempty"`
	Nodes         []*TMLedgerNode        `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	RequestCookie uint32                 `protobuf:"varint,5,opt,name=request_cookie,json=requestCookie,proto3" json:"request_cookie,omitempty"`
	Error         TMReplyError           `protobuf:"varint,6,opt,name=error,proto3,enum=protocol.TMReplyError" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMLedgerData) Reset() {
	*x = TMLedgerData{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMLedgerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMLedgerData) ProtoMessage() {}

func (x *TMLedgerData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMLedgerData.ProtoReflect.Descriptor instead.
func (*TMLedgerData) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{20}
}

func (x *TMLedgerData) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

func (x *TMLedgerData) GetLedgerSeq() uint32 {
	if x != nil {
		return x.LedgerSeq
	}
	return 0
}

func (x *TMLedgerData) GetType() TMLedgerInfoType {
	if x != nil {
		return x.Type
	}
	return TMLedgerInfoType_liBASE
}

func (x *TMLedgerData) GetNodes() []*TMLedgerNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TMLedgerData) GetRequestCookie() uint32 {
	if x != nil {
		return x.RequestCookie
	}
	return 0
}

func (x *TMLedgerData) GetError() TMReplyError {
	if x != nil {
		return x.Error
	}
	return TMReplyError_reNO_ERROR
}

// Ping/Pong
type TMPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TMPing_PingType        `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.TMPing_PingType" json:"type,omitempty"`
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	PingTime      uint64                 `protobuf:"varint,3,opt,name=ping_time,json=pingTime,proto3" json:"ping_time,omitempty"`
	NetTime       uint64                 `protobuf:"varint,4,opt,name=net_time,json=netTime,proto3" json:"net_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMPing) Reset() {
	*x = TMPing{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMPing) ProtoMessage() {}

func (x *TMPing) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMPing.ProtoReflect.Descriptor instead.
func (*TMPing) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{21}
}

func (x *TMPing) GetType() TMPing_PingType {
	if x != nil {
		return x.Type
	}
	return TMPing_ptPING
}

func (x *TMPing) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TMPing) GetPingTime() uint64 {
	if x != nil {
		return x.PingTime
	}
	return 0
}

func (x *TMPing) GetNetTime() uint64 {
	if x != nil {
		return x.NetTime
	}
	return 0
}

// Squelch for reduce-relay
type TMSquelch struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Squelch         bool                   `protobuf:"varint,1,opt,name=squelch,proto3" json:"squelch,omitempty"`
	ValidatorPubKey []byte                 `protobuf:"bytes,2,opt,name=validator_pub_key,json=validatorPubKey,proto3" json:"validator_pub_key,omitempty"`
	SquelchDuration uint32                 `protobuf:"varint,3,opt,name=squelch_duration,json=squelchDuration,proto3" json:"squelch_duration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TMSquelch) Reset() {
	*x = TMSquelch{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMSquelch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMSquelch) ProtoMessage() {}

func (x *TMSquelch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMSquelch.ProtoReflect.Descriptor instead.
func (*TMSquelch) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{22}
}

func (x *TMSquelch) GetSquelch() bool {
	if x != nil {
		return x.Squelch
	}
	return false
}

func (x *TMSquelch) GetValidatorPubKey() []byte {
	if x != nil {
		return x.ValidatorPubKey
	}
	return nil
}

func (x *TMSquelch) GetSquelchDuration() uint32 {
	if x != nil {
		return x.SquelchDuration
	}
	return 0
}

// Proof path request/response
type TMProofPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LedgerHash    []byte                 `protobuf:"bytes,2,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	Type          TMLedgerMapType        `protobuf:"varint,3,opt,name=type,proto3,enum=protocol.TMLedgerMapType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMProofPathRequest) Reset() {
	*x = TMProofPathRequest{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMProofPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMProofPathRequest) ProtoMessage() {}

func (x *TMProofPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMProofPathRequest.ProtoReflect.Descriptor instead.
func (*TMProofPathRequest) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{23}
}

func (x *TMProofPathRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *TMProofPathRequest) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

func (x *TMProofPathRequest) GetType() TMLedgerMapType {
	if x != nil {
		return x.Type
	}
	return TMLedgerMapType_lmUNKNOWN
}

type TMProofPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LedgerHash    []byte                 `protobuf:"bytes,2,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	Type          TMLedgerMapType        `protobuf:"varint,3,opt,name=type,proto3,enum=protocol.TMLedgerMapType" json:"type,omitempty"`
	LedgerHeader  []byte                 `protobuf:"bytes,4,opt,name=ledger_header,json=ledgerHeader,proto3" json:"ledger_header,omitempty"`
	Path          [][]byte               `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	Error         TMReplyError           `protobuf:"varint,6,opt,name=error,proto3,enum=protocol.TMReplyError" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMProofPathResponse) Reset() {
	*x = TMProofPathResponse{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMProofPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMProofPathResponse) ProtoMessage() {}

func (x *TMProofPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMProofPathResponse.ProtoReflect.Descriptor instead.
func (*TMProofPathResponse) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{24}
}

func (x *TMProofPathResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *TMProofPathResponse) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

func (x *TMProofPathResponse) GetType() TMLedgerMapType {
	if x != nil {
		return x.Type
	}
	return TMLedgerMapType_lmUNKNOWN
}

func (x *TMProofPathResponse) GetLedgerHeader() []byte {
	if x != nil {
		return x.LedgerHeader
	}
	return nil
}

func (x *TMProofPathResponse) GetPath() [][]byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *TMProofPathResponse) GetError() TMReplyError {
	if x != nil {
		return x.Error
	}
	return TMReplyError_reNO_ERROR
}

// Replay delta for ledger sync
type TMReplayDeltaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerHash    []byte                 `protobuf:"bytes,1,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMReplayDeltaRequest) Reset() {
	*x = TMReplayDeltaRequest{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMReplayDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMReplayDeltaRequest) ProtoMessage() {}

func (x *TMReplayDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMReplayDeltaRequest.ProtoReflect.Descriptor instead.
func (*TMReplayDeltaRequest) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{25}
}

func (x *TMReplayDeltaRequest) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

type TMReplayDeltaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerHash    []byte                 `protobuf:"bytes,1,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	LedgerHeader  []byte                 `protobuf:"bytes,2,opt,name=ledger_header,json=ledgerHeader,proto3" json:"ledger_header,omitempty"`
	Transaction   [][]byte               `protobuf:"bytes,3,rep,name=transaction,proto3" json:"transaction,omitempty"`
	Error         TMReplyError           `protobuf:"varint,4,opt,name=error,proto3,enum=protocol.TMReplyError" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMReplayDeltaResponse) Reset() {
	*x = TMReplayDeltaResponse{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMReplayDeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMReplayDeltaResponse) ProtoMessage() {}

func (x *TMReplayDeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMReplayDeltaResponse.ProtoReflect.Descriptor instead.
func (*TMReplayDeltaResponse) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{26}
}

func (x *TMReplayDeltaResponse) GetLedgerHash() []byte {
	if x != nil {
		return x.LedgerHash
	}
	return nil
}

func (x *TMReplayDeltaResponse) GetLedgerHeader() []byte {
	if x != nil {
		return x.LedgerHeader
	}
	return nil
}

func (x *TMReplayDeltaResponse) GetTransaction() [][]byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TMReplayDeltaResponse) GetError() TMReplyError {
	if x != nil {
		return x.Error
	}
	return TMReplyError_reNO_ERROR
}

// Have transactions (reduce-relay)
type TMHaveTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMHaveTransactions) Reset() {
	*x = TMHaveTransactions{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMHaveTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMHaveTransactions) ProtoMessage() {}

func (x *TMHaveTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMHaveTransactions.ProtoReflect.Descriptor instead.
func (*TMHaveTransactions) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{27}
}

func (x *TMHaveTransactions) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type TMEndpoints_TMEndpointv2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Hops          uint32                 `protobuf:"varint,2,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMEndpoints_TMEndpointv2) Reset() {
	*x = TMEndpoints_TMEndpointv2{}
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMEndpoints_TMEndpointv2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMEndpoints_TMEndpointv2) ProtoMessage() {}

func (x *TMEndpoints_TMEndpointv2) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peermanagement_proto_ripple_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMEndpoints_TMEndpointv2.ProtoReflect.Descriptor instead.
func (*TMEndpoints_TMEndpointv2) Descriptor() ([]byte, []int) {
	return file_internal_peermanagement_proto_ripple_proto_rawDescGZIP(), []int{15, 0}
}

func (x *TMEndpoints_TMEndpointv2) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *TMEndpoints_TMEndpointv2) GetHops() uint32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

var File_internal_peermanagement_proto_ripple_proto protoreflect.FileDescriptor

const file_internal_peermanagement_proto_ripple_proto_rawDesc = "" +
	"\n" +
	"*internal/peermanagement/proto/ripple.proto\x12\bprotocol\"(\n" +
	"\n" +
	"TMManifest\x12\x1a\n" +
	"\bstobject\x18\x01 \x01(\fR\bstobject\"U\n" +
	"\vTMManifests\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.protocol.TMManifestR\x04list\x12\x1c\n" +
	"\ahistory\x18\x02 \x01(\bB\x02\x18\x01R\ahistory\"\xa3\x01\n" +
	"\rTMClusterNode\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vreport_time\x18\x02 \x01(\rR\n" +
	"reportTime\x12\x1b\n" +
	"\tnode_load\x18\x03 \x01(\rR\bnodeLoad\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"L\n" +
	"\fTMLoadSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\rR\x04cost\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"\x84\x01\n" +
	"\tTMCluster\x12<\n" +
	"\rcluster_nodes\x18\x01 \x03(\v2\x17.protocol.TMClusterNodeR\fclusterNodes\x129\n" +
	"\fload_sources\x18\x02 \x03(\v2\x16.protocol.TMLoadSourceR\vloadSources\",\n" +
	"\vTMPublicKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\"\xb6\x01\n" +
	"\rTMTransaction\x12'\n" +
	"\x0fraw_transaction\x18\x01 \x01(\fR\x0erawTransaction\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.protocol.TransactionStatusR\x06status\x12+\n" +
	"\x11receive_timestamp\x18\x03 \x01(\x04R\x10receiveTimestamp\x12\x1a\n" +
	"\bdeferred\x18\x04 \x01(\bR\bdeferred\"M\n" +
	"\x0eTMTransactions\x12;\n" +
	"\ftransactions\x18\x01 \x03(\v2\x17.protocol.TMTransactionR\ftransactions\"\xc4\x02\n" +
	"\x0eTMStatusChange\x123\n" +
	"\n" +
	"new_status\x18\x01 \x01(\x0e2\x14.protocol.NodeStatusR\tnewStatus\x120\n" +
	"\tnew_event\x18\x02 \x01(\x0e2\x13.protocol.NodeEventR\bnewEvent\x12\x1d\n" +
	"\n" +
	"ledger_seq\x18\x03 \x01(\rR\tledgerSeq\x12\x1f\n" +
	"\vledger_hash\x18\x04 \x01(\fR\n" +
	"ledgerHash\x120\n" +
	"\x14ledger_hash_previous\x18\x05 \x01(\fR\x12ledgerHashPrevious\x12!\n" +
	"\fnetwork_time\x18\x06 \x01(\x04R\vnetworkTime\x12\x1b\n" +
	"\tfirst_seq\x18\a \x01(\rR\bfirstSeq\x12\x19\n" +
	"\blast_seq\x18\b \x01(\rR\alastSeq\"\x8a\x03\n" +
	"\fTMProposeSet\x12\x1f\n" +
	"\vpropose_seq\x18\x01 \x01(\rR\n" +
	"proposeSeq\x12&\n" +
	"\x0fcurrent_tx_hash\x18\x02 \x01(\fR\rcurrentTxHash\x12 \n" +
	"\fnode_pub_key\x18\x03 \x01(\fR\n" +
	"nodePubKey\x12\x1d\n" +
	"\n" +
	"close_time\x18\x04 \x01(\rR\tcloseTime\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12'\n" +
	"\x0fprevious_ledger\x18\x06 \x01(\fR\x0epreviousLedger\x12/\n" +
	"\x11checked_signature\x18\a \x01(\bB\x02\x18\x01R\x10checkedSignature\x12-\n" +
	"\x12added_transactions\x18\n" +
	" \x03(\fR\x11addedTransactions\x121\n" +
	"\x14removed_transactions\x18\v \x03(\fR\x13removedTransactions\x12\x16\n" +
	"\x04hops\x18\f \x01(\rB\x02\x18\x01R\x04hops\"Y\n" +
	"\x14TMHaveTransactionSet\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.protocol.TxSetStatusR\x06status\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"y\n" +
	"\x0fTMValidatorList\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\x12\x12\n" +
	"\x04blob\x18\x02 \x01(\fR\x04blob\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\"a\n" +
	"\x11ValidatorBlobInfo\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\x12\x12\n" +
	"\x04blob\x18\x02 \x01(\fR\x04blob\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x84\x01\n" +
	"\x19TMValidatorListCollection\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1a\n" +
	"\bmanifest\x18\x02 \x01(\fR\bmanifest\x121\n" +
	"\x05blobs\x18\x03 \x03(\v2\x1b.protocol.ValidatorBlobInfoR\x05blobs\"w\n" +
	"\fTMValidation\x12\x1e\n" +
	"\n" +
	"validation\x18\x01 \x01(\fR\n" +
	"validation\x12/\n" +
	"\x11checked_signature\x18\x02 \x01(\bB\x02\x18\x01R\x10checkedSignature\x12\x16\n" +
	"\x04hops\x18\x03 \x01(\rB\x02\x18\x01R\x04hops\"\xae\x01\n" +
	"\vTMEndpoints\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12E\n" +
	"\fendpoints_v2\x18\x03 \x03(\v2\".protocol.TMEndpoints.TMEndpointv2R\vendpointsV2\x1a>\n" +
	"\fTMEndpointv2\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04hops\x18\x02 \x01(\rR\x04hops\"\x87\x01\n" +
	"\x0fTMIndexedObject\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\fR\x06nodeId\x12\x14\n" +
	"\x05index\x18\x03 \x01(\fR\x05index\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"ledger_seq\x18\x05 \x01(\rR\tledgerSeq\"\xcd\x01\n" +
	"\x11TMGetObjectByHash\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.protocol.ObjectTypeR\x04type\x12\x14\n" +
	"\x05query\x18\x02 \x01(\bR\x05query\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\rR\x03seq\x12\x1f\n" +
	"\vledger_hash\x18\x04 \x01(\fR\n" +
	"ledgerHash\x12\x10\n" +
	"\x03fat\x18\x05 \x01(\bR\x03fat\x123\n" +
	"\aobjects\x18\x06 \x03(\v2\x19.protocol.TMIndexedObjectR\aobjects\"B\n" +
	"\fTMLedgerNode\x12\x1a\n" +
	"\bnodedata\x18\x01 \x01(\fR\bnodedata\x12\x16\n" +
	"\x06nodeid\x18\x02 \x01(\fR\x06nodeid\"\xc6\x02\n" +
	"\vTMGetLedger\x120\n" +
	"\x05itype\x18\x01 \x01(\x0e2\x1a.protocol.TMLedgerInfoTypeR\x05itype\x12,\n" +
	"\x05ltype\x18\x02 \x01(\x0e2\x16.protocol.TMLedgerTypeR\x05ltype\x12\x1f\n" +
	"\vledger_hash\x18\x03 \x01(\fR\n" +
	"ledgerHash\x12\x1d\n" +
	"\n" +
	"ledger_seq\x18\x04 \x01(\rR\tledgerSeq\x12\x19\n" +
	"\bnode_ids\x18\x05 \x03(\fR\anodeIds\x12%\n" +
	"\x0erequest_cookie\x18\x06 \x01(\x04R\rrequestCookie\x124\n" +
	"\n" +
	"query_type\x18\a \x01(\x0e2\x15.protocol.TMQueryTypeR\tqueryType\x12\x1f\n" +
	"\vquery_depth\x18\b \x01(\rR\n" +
	"queryDepth\"\x81\x02\n" +
	"\fTMLedgerData\x12\x1f\n" +
	"\vledger_hash\x18\x01 \x01(\fR\n" +
	"ledgerHash\x12\x1d\n" +
	"\n" +
	"ledger_seq\x18\x02 \x01(\rR\tledgerSeq\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.protocol.TMLedgerInfoTypeR\x04type\x12,\n" +
	"\x05nodes\x18\x04 \x03(\v2\x16.protocol.TMLedgerNodeR\x05nodes\x12%\n" +
	"\x0erequest_cookie\x18\x05 \x01(\rR\rrequestCookie\x12,\n" +
	"\x05error\x18\x06 \x01(\x0e2\x16.protocol.TMReplyErrorR\x05error\"\xa5\x01\n" +
	"\x06TMPing\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.protocol.TMPing.PingTypeR\x04type\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x1b\n" +
	"\tping_time\x18\x03 \x01(\x04R\bpingTime\x12\x19\n" +
	"\bnet_time\x18\x04 \x01(\x04R\anetTime\"\"\n" +
	"\bPingType\x12\n" +
	"\n" +
	"\x06ptPING\x10\x00\x12\n" +
	"\n" +
	"\x06ptPONG\x10\x01\"|\n" +
	"\tTMSquelch\x12\x18\n" +
	"\asquelch\x18\x01 \x01(\bR\asquelch\x12*\n" +
	"\x11validator_pub_key\x18\x02 \x01(\fR\x0fvalidatorPubKey\x12)\n" +
	"\x10squelch_duration\x18\x03 \x01(\rR\x0fsquelchDuration\"v\n" +
	"\x12TMProofPathRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1f\n" +
	"\vledger_hash\x18\x02 \x01(\fR\n" +
	"ledgerHash\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.protocol.TMLedgerMapTypeR\x04type\"\xde\x01\n" +
	"\x13TMProofPathResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1f\n" +
	"\vledger_hash\x18\x02 \x01(\fR\n" +
	"ledgerHash\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.protocol.TMLedgerMapTypeR\x04type\x12#\n" +
	"\rledger_header\x18\x04 \x01(\fR\fledgerHeader\x12\x12\n" +
	"\x04path\x18\x05 \x03(\fR\x04path\x12,\n" +
	"\x05error\x18\x06 \x01(\x0e2\x16.protocol.TMReplyErrorR\x05error\"7\n" +
	"\x14TMReplayDeltaRequest\x12\x1f\n" +
	"\vledger_hash\x18\x01 \x01(\fR\n" +
	"ledgerHash\"\xad\x01\n" +
	"\x15TMReplayDeltaResponse\x12\x1f\n" +
	"\vledger_hash\x18\x01 \x01(\fR\n" +
	"ledgerHash\x12#\n" +
	"\rledger_header\x18\x02 \x01(\fR\fledgerHeader\x12 \n" +
	"\vtransaction\x18\x03 \x03(\fR\vtransaction\x12,\n" +
	"\x05error\x18\x04 \x01(\x0e2\x16.protocol.TMReplyErrorR\x05error\",\n" +
	"\x12TMHaveTransactions\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes*\xc7\x03\n" +
	"\vMessageType\x12\r\n" +
	"\tmtUNKNOWN\x10\x00\x12\x0f\n" +
	"\vmtMANIFESTS\x10\x02\x12\n" +
	"\n" +
	"\x06mtPING\x10\x03\x12\r\n" +
	"\tmtCLUSTER\x10\x05\x12\x0f\n" +
	"\vmtENDPOINTS\x10\x0f\x12\x11\n" +
	"\rmtTRANSACTION\x10\x1e\x12\x10\n" +
	"\fmtGET_LEDGER\x10\x1f\x12\x11\n" +
	"\rmtLEDGER_DATA\x10 \x12\x14\n" +
	"\x10mtPROPOSE_LEDGER\x10!\x12\x13\n" +
	"\x0fmtSTATUS_CHANGE\x10\"\x12\x0e\n" +
	"\n" +
	"mtHAVE_SET\x10#\x12\x10\n" +
	"\fmtVALIDATION\x10)\x12\x11\n" +
	"\rmtGET_OBJECTS\x10*\x12\x13\n" +
	"\x0fmtVALIDATORLIST\x106\x12\r\n" +
	"\tmtSQUELCH\x107\x12\x1d\n" +
	"\x19mtVALIDATORLISTCOLLECTION\x108\x12\x14\n" +
	"\x10mtPROOF_PATH_REQ\x109\x12\x19\n" +
	"\x15mtPROOF_PATH_RESPONSE\x10:\x12\x16\n" +
	"\x12mtREPLAY_DELTA_REQ\x10;\x12\x1b\n" +
	"\x17mtREPLAY_DELTA_RESPONSE\x10<\x12\x17\n" +
	"\x13mtHAVE_TRANSACTIONS\x10?\x12\x12\n" +
	"\x0emtTRANSACTIONS\x10@*\xb0\x01\n" +
	"\x11TransactionStatus\x12\r\n" +
	"\ttsUNKNOWN\x10\x00\x12\t\n" +
	"\x05tsNEW\x10\x01\x12\r\n" +
	"\ttsCURRENT\x10\x02\x12\x0e\n" +
	"\n" +
	"tsCOMMITED\x10\x03\x12\x15\n" +
	"\x11tsREJECT_CONFLICT\x10\x04\x12\x14\n" +
	"\x10tsREJECT_INVALID\x10\x05\x12\x12\n" +
	"\x0etsREJECT_FUNDS\x10\x06\x12\x0e\n" +
	"\n" +
	"tsHELD_SEQ\x10\a\x12\x11\n" +
	"\rtsHELD_LEDGER\x10\b*r\n" +
	"\n" +
	"NodeStatus\x12\r\n" +
	"\tnsUNKNOWN\x10\x00\x12\x10\n" +
	"\fnsCONNECTING\x10\x01\x12\x0f\n" +
	"\vnsCONNECTED\x10\x02\x12\x10\n" +
	"\fnsMONITORING\x10\x03\x12\x10\n" +
	"\fnsVALIDATING\x10\x04\x12\x0e\n" +
	"\n" +
	"nsSHUTTING\x10\x05*o\n" +
	"\tNodeEvent\x12\r\n" +
	"\tneUNKNOWN\x10\x00\x12\x14\n" +
	"\x10neCLOSING_LEDGER\x10\x01\x12\x15\n" +
	"\x11neACCEPTED_LEDGER\x10\x02\x12\x15\n" +
	"\x11neSWITCHED_LEDGER\x10\x03\x12\x0f\n" +
	"\vneLOST_SYNC\x10\x04*G\n" +
	"\vTxSetStatus\x12\x11\n" +
	"\rtsUNKNOWN_SET\x10\x00\x12\n" +
	"\n" +
	"\x06tsHAVE\x10\x01\x12\r\n" +
	"\ttsCAN_GET\x10\x02\x12\n" +
	"\n" +
	"\x06tsNEED\x10\x03*\x9e\x01\n" +
	"\n" +
	"ObjectType\x12\r\n" +
	"\totUNKNOWN\x10\x00\x12\f\n" +
	"\botLEDGER\x10\x01\x12\x11\n" +
	"\rotTRANSACTION\x10\x02\x12\x16\n" +
	"\x12otTRANSACTION_NODE\x10\x03\x12\x10\n" +
	"\fotSTATE_NODE\x10\x04\x12\x10\n" +
	"\fotCAS_OBJECT\x10\x05\x12\x10\n" +
	"\fotFETCH_PACK\x10\x06\x12\x12\n" +
	"\x0eotTRANSACTIONS\x10\a*P\n" +
	"\x10TMLedgerInfoType\x12\n" +
	"\n" +
	"\x06liBASE\x10\x00\x12\r\n" +
	"\tliTX_NODE\x10\x01\x12\r\n" +
	"\tliAS_NODE\x10\x02\x12\x12\n" +
	"\x0eliTS_CANDIDATE\x10\x03*;\n" +
	"\fTMLedgerType\x12\x0e\n" +
	"\n" +
	"ltACCEPTED\x10\x00\x12\r\n" +
	"\tltCURRENT\x10\x01\x12\f\n" +
	"\bltCLOSED\x10\x02*\x1d\n" +
	"\vTMQueryType\x12\x0e\n" +
	"\n" +
	"qtINDIRECT\x10\x00*Q\n" +
	"\fTMReplyError\x12\x0e\n" +
	"\n" +
	"reNO_ERROR\x10\x00\x12\x0f\n" +
	"\vreNO_LEDGER\x10\x01\x12\r\n" +
	"\treNO_NODE\x10\x02\x12\x11\n" +
	"\rreBAD_REQUEST\x10\x03*H\n" +
	"\x0fTMLedgerMapType\x12\r\n" +
	"\tlmUNKNOWN\x10\x00\x12\x11\n" +
	"\rlmTRANSACTION\x10\x01\x12\x13\n" +
	"\x0flmACCOUNT_STATE\x10\x02B:Z8github.com/LeJamon/goXRPLd/internal/peermanagement/protob\x06proto3"

var (
	file_internal_peermanagement_proto_ripple_proto_rawDescOnce sync.Once
	file_internal_peermanagement_proto_ripple_proto_rawDescData []byte
)

func file_internal_peermanagement_proto_ripple_proto_rawDescGZIP() []byte {
	file_internal_peermanagement_proto_ripple_proto_rawDescOnce.Do(func() {
		file_internal_peermanagement_proto_ripple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_peermanagement_proto_ripple_proto_rawDesc), len(file_internal_peermanagement_proto_ripple_proto_rawDesc)))
	})
	return file_internal_peermanagement_proto_ripple_proto_rawDescData
}

var file_internal_peermanagement_proto_ripple_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_internal_peermanagement_proto_ripple_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_internal_peermanagement_proto_ripple_proto_goTypes = []any{
	(MessageType)(0),                  // 0: protocol.MessageType
	(TransactionStatus)(0),            // 1: protocol.TransactionStatus
	(NodeStatus)(0),                   // 2: protocol.NodeStatus
	(NodeEvent)(0),                    // 3: protocol.NodeEvent
	(TxSetStatus)(0),                  // 4: protocol.TxSetStatus
	(ObjectType)(0),                   // 5: protocol.ObjectType
	(TMLedgerInfoType)(0),             // 6: protocol.TMLedgerInfoType
	(TMLedgerType)(0),                 // 7: protocol.TMLedgerType
	(TMQueryType)(0),                  // 8: protocol.TMQueryType
	(TMReplyError)(0),                 // 9: protocol.TMReplyError
	(TMLedgerMapType)(0),              // 10: protocol.TMLedgerMapType
	(TMPing_PingType)(0),              // 11: protocol.TMPing.PingType
	(*TMManifest)(nil),                // 12: protocol.TMManifest
	(*TMManifests)(nil),               // 13: protocol.TMManifests
	(*TMClusterNode)(nil),             // 14: protocol.TMClusterNode
	(*TMLoadSource)(nil),              // 15: protocol.TMLoadSource
	(*TMCluster)(nil),                 // 16: protocol.TMCluster
	(*TMPublicKey)(nil),               // 17: protocol.TMPublicKey
	(*TMTransaction)(nil),             // 18: protocol.TMTransaction
	(*TMTransactions)(nil),            // 19: protocol.TMTransactions
	(*TMStatusChange)(nil),            // 20: protocol.TMStatusChange
	(*TMProposeSet)(nil),              // 21: protocol.TMProposeSet
	(*TMHaveTransactionSet)(nil),      // 22: protocol.TMHaveTransactionSet
	(*TMValidatorList)(nil),           // 23: protocol.TMValidatorList
	(*ValidatorBlobInfo)(nil),         // 24: protocol.ValidatorBlobInfo
	(*TMValidatorListCollection)(nil), // 25: protocol.TMValidatorListCollection
	(*TMValidation)(nil),              // 26: protocol.TMValidation
	(*TMEndpoints)(nil),               // 27: protocol.TMEndpoints
	(*TMIndexedObject)(nil),           // 28: protocol.TMIndexedObject
	(*TMGetObjectByHash)(nil),         // 29: protocol.TMGetObjectByHash
	(*TMLedgerNode)(nil),              // 30: protocol.TMLedgerNode
	(*TMGetLedger)(nil),               // 31: protocol.TMGetLedger
	(*TMLedgerData)(nil),              // 32: protocol.TMLedgerData
	(*TMPing)(nil),                    // 33: protocol.TMPing
	(*TMSquelch)(nil),                 // 34: protocol.TMSquelch
	(*TMProofPathRequest)(nil),        // 35: protocol.TMProofPathRequest
	(*TMProofPathResponse)(nil),       // 36: protocol.TMProofPathResponse
	(*TMReplayDeltaRequest)(nil),      // 37: protocol.TMReplayDeltaRequest
	(*TMReplayDeltaResponse)(nil),     // 38: protocol.TMReplayDeltaResponse
	(*TMHaveTransactions)(nil),        // 39: protocol.TMHaveTransactions
	(*TMEndpoints_TMEndpointv2)(nil),  // 40: protocol.TMEndpoints.TMEndpointv2
}
var file_internal_peermanagement_proto_ripple_proto_depIdxs = []int32{
	12, // 0: protocol.TMManifests.list:type_name -> protocol.TMManifest
	14, // 1: protocol.TMCluster.cluster_nodes:type_name -> protocol.TMClusterNode
	15, // 2: protocol.TMCluster.load_sources:type_name -> protocol.TMLoadSource
	1,  // 3: protocol.TMTransaction.status:type_name -> protocol.TransactionStatus
	18, // 4: protocol.TMTransactions.transactions:type_name -> protocol.TMTransaction
	2,  // 5: protocol.TMStatusChange.new_status:type_name -> protocol.NodeStatus
	3,  // 6: protocol.TMStatusChange.new_event:type_name -> protocol.NodeEvent
	4,  // 7: protocol.TMHaveTransactionSet.status:type_name -> protocol.TxSetStatus
	24, // 8: protocol.TMValidatorListCollection.blobs:type_name -> protocol.ValidatorBlobInfo
	40, // 9: protocol.TMEndpoints.endpoints_v2:type_name -> protocol.TMEndpoints.TMEndpointv2
	5,  // 10: protocol.TMGetObjectByHash.type:type_name -> protocol.ObjectType
	28, // 11: protocol.TMGetObjectByHash.objects:type_name -> protocol.TMIndexedObject
	6,  // 12: protocol.TMGetLedger.itype:type_name -> protocol.TMLedgerInfoType
	7,  // 13: protocol.TMGetLedger.ltype:type_name -> protocol.TMLedgerType
	8,  // 14: protocol.TMGetLedger.query_type:type_name -> protocol.TMQueryType
	6,  // 15: protocol.TMLedgerData.type:type_name -> protocol.TMLedgerInfoType
	30, // 16: protocol.TMLedgerData.nodes:type_name -> protocol.TMLedgerNode
	9,  // 17: protocol.TMLedgerData.error:type_name -> protocol.TMReplyError
	11, // 18: protocol.TMPing.type:type_name -> protocol.TMPing.PingType
	10, // 19: protocol.TMProofPathRequest.type:type_name -> protocol.TMLedgerMapType
	10, // 20: protocol.TMProofPathResponse.type:type_name -> protocol.TMLedgerMapType
	9,  // 21: protocol.TMProofPathResponse.error:type_name -> protocol.TMReplyError
	9,  // 22: protocol.TMReplayDeltaResponse.error:type_name -> protocol.TMReplyError
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_internal_peermanagement_proto_ripple_proto_init() }
func file_internal_peermanagement_proto_ripple_proto_init() {
	if File_internal_peermanagement_proto_ripple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_peermanagement_proto_ripple_proto_rawDesc), len(file_internal_peermanagement_proto_ripple_proto_rawDesc)),
			NumEnums:      12,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_peermanagement_proto_ripple_proto_goTypes,
		DependencyIndexes: file_internal_peermanagement_proto_ripple_proto_depIdxs,
		EnumInfos:         file_internal_peermanagement_proto_ripple_proto_enumTypes,
		MessageInfos:      file_internal_peermanagement_proto_ripple_proto_msgTypes,
	}.Build()
	File_internal_peermanagement_proto_ripple_proto = out.File
	file_internal_peermanagement_proto_ripple_proto_goTypes = nil
	file_internal_peermanagement_proto_ripple_proto_depIdxs = nil
}
